import chromadb
from chromadb.utils import embedding_functions
import os
from dotenv import load_dotenv


DB_DIR = "./chroma_db"
# Load the environment variables from the .env file
load_dotenv() 

def init_vector_db():
    # Initialize persistent ChromaDB client
    client = chromadb.PersistentClient(path=DB_DIR)
    
    # Use standard default sentence transformer embedding or OpenAI embeddings
    sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

    collection = client.get_or_create_collection(
        name="sql_examples",
        embedding_function=sentence_transformer_ef
    )

    # 32 High-Quality E-Commerce Example Pairs covering all query types
    examples = [
        # =============================================
        # SELECT_SIMPLE — Basic retrieval & filtering
        # =============================================
        {
            "id": "ex_1",
            "question": "Show all active products in the store.",
            "sql": "SELECT product_id, product_name, unit_price FROM products WHERE is_active = 1;"
        },
        {
            "id": "ex_2",
            "question": "List all customers from Chicago.",
            "sql": "SELECT customer_id, first_name, last_name, email FROM customers WHERE city = 'Chicago';"
        },
        {
            "id": "ex_3",
            "question": "Which products are low in stock (less than 20 items remaining)?",
            "sql": "SELECT product_id, product_name, stock_quantity FROM products WHERE stock_quantity < 20 AND is_active = 1 ORDER BY stock_quantity ASC;"
        },
        {
            "id": "ex_4",
            "question": "List all products in category 2 with stock greater than 50.",
            "sql": "SELECT product_id, product_name, stock_quantity FROM products WHERE category_id = 2 AND stock_quantity > 50;"
        },
        {
            "id": "ex_5",
            "question": "List the top 5 most expensive products.",
            "sql": "SELECT product_id, product_name, unit_price FROM products ORDER BY unit_price DESC LIMIT 5;"
        },
        {
            "id": "ex_6",
            "question": "Find all customers whose email address ends with @gmail.com.",
            "sql": "SELECT customer_id, first_name, last_name, email FROM customers WHERE email LIKE '%@gmail.com';"
        },
        {
            "id": "ex_7",
            "question": "Show all payments that have a pending or failed status.",
            "sql": "SELECT payment_id, order_id, amount, payment_status FROM payments WHERE payment_status IN ('pending', 'failed');"
        },

        # =============================================
        # SELECT_AGGREGATE — COUNT, SUM, AVG, GROUP BY
        # =============================================
        {
            "id": "ex_8",
            "question": "What is the total number of orders placed?",
            "sql": "SELECT COUNT(order_id) AS total_orders FROM orders;"
        },
        {
            "id": "ex_9",
            "question": "What is the average price of all active products?",
            "sql": "SELECT AVG(unit_price) AS avg_price FROM products WHERE is_active = 1;"
        },
        {
            "id": "ex_10",
            "question": "Count how many orders exist for each status.",
            "sql": "SELECT status, COUNT(order_id) AS order_count FROM orders GROUP BY status;"
        },
        {
            "id": "ex_11",
            "question": "Find the total revenue generated by each payment method.",
            "sql": "SELECT payment_method, SUM(amount) AS total_revenue FROM payments WHERE payment_status = 'success' GROUP BY payment_method ORDER BY total_revenue DESC;"
        },
        {
            "id": "ex_12",
            "question": "What is the average order value across all completed orders?",
            "sql": "SELECT AVG(total_amount) AS avg_order_value FROM orders WHERE status = 'completed';"
        },
        {
            "id": "ex_13",
            "question": "Calculate total revenue generated from successful payments.",
            "sql": "SELECT SUM(amount) AS total_revenue FROM payments WHERE payment_status = 'success';"
        },
        {
            "id": "ex_14",
            "question": "What is the average order value (AOV) per payment method?",
            "sql": "SELECT p.payment_method, AVG(p.amount) AS avg_payment_amount FROM payments p WHERE p.payment_status = 'success' GROUP BY p.payment_method ORDER BY avg_payment_amount DESC;"
        },
        {
            "id": "ex_15",
            "question": "How many customers are there in each country?",
            "sql": "SELECT country, COUNT(customer_id) AS customer_count FROM customers GROUP BY country ORDER BY customer_count DESC;"
        },

        # =============================================
        # SELECT_JOIN — Multi-table queries
        # =============================================
        {
            "id": "ex_16",
            "question": "What are the top 5 highest spending customers?",
            "sql": "SELECT c.customer_id, c.first_name, c.last_name, SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id WHERE o.status = 'completed' GROUP BY c.customer_id ORDER BY total_spent DESC LIMIT 5;"
        },
        {
            "id": "ex_17",
            "question": "Which product categories generated the most total revenue?",
            "sql": "SELECT cat.category_name, SUM(oi.subtotal) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id JOIN orders o ON oi.order_id = o.order_id WHERE o.status != 'canceled' GROUP BY cat.category_name ORDER BY category_revenue DESC;"
        },
        {
            "id": "ex_18",
            "question": "List each product along with its category name.",
            "sql": "SELECT p.product_name, c.category_name FROM products p JOIN categories c ON p.category_id = c.category_id;"
        },
        {
            "id": "ex_19",
            "question": "Find all completed orders placed with PayPal.",
            "sql": "SELECT o.order_id, o.customer_id, p.amount FROM orders o JOIN payments p ON o.order_id = p.order_id WHERE o.status = 'completed' AND p.payment_method = 'paypal' AND p.payment_status = 'success';"
        },
        {
            "id": "ex_20",
            "question": "Find order details for order ID 10 including product names and subtotal.",
            "sql": "SELECT oi.order_id, p.product_name, oi.quantity, oi.subtotal FROM order_items oi JOIN products p ON oi.product_id = p.product_id WHERE oi.order_id = 10;"
        },
        {
            "id": "ex_21",
            "question": "Show the top 3 customers in Chicago ordered by total number of orders.",
            "sql": "SELECT c.customer_id, c.first_name, c.last_name, COUNT(o.order_id) AS order_count FROM customers c JOIN orders o ON c.customer_id = o.customer_id WHERE c.city = 'Chicago' GROUP BY c.customer_id ORDER BY order_count DESC LIMIT 3;"
        },
        {
            "id": "ex_22",
            "question": "What is the single most popular product by total quantity sold?",
            "sql": "SELECT p.product_name, SUM(oi.quantity) AS total_quantity FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id ORDER BY total_quantity DESC LIMIT 1;"
        },
        {
            "id": "ex_23",
            "question": "Show customer names and total quantity of items purchased for order ID 1.",
            "sql": "SELECT c.first_name, c.last_name, SUM(oi.quantity) AS total_items FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_id = 1 GROUP BY c.customer_id;"
        },

        # =============================================
        # LEFT JOIN — Missing/Unmatched Records
        # =============================================
        {
            "id": "ex_24",
            "question": "List all customers who have never placed an order.",
            "sql": "SELECT c.customer_id, c.first_name, c.last_name FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id WHERE o.order_id IS NULL;"
        },
        {
            "id": "ex_25",
            "question": "Find products that have never been ordered.",
            "sql": "SELECT p.product_id, p.product_name FROM products p LEFT JOIN order_items oi ON p.product_id = oi.product_id WHERE oi.order_item_id IS NULL;"
        },

        # =============================================
        # HAVING — Aggregated threshold filtering
        # =============================================
        {
            "id": "ex_26",
            "question": "Find customers who have spent more than 500 dollars in total.",
            "sql": "SELECT c.customer_id, c.first_name, c.last_name, SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id HAVING total_spent > 500;"
        },
        {
            "id": "ex_27",
            "question": "Which categories have generated more than 10000 in revenue?",
            "sql": "SELECT cat.category_name, SUM(oi.subtotal) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY cat.category_name HAVING category_revenue > 10000 ORDER BY category_revenue DESC;"
        },

        # =============================================
        # SELECT_TEMPORAL — Date/time queries
        # =============================================
        {
            "id": "ex_28",
            "question": "How many orders were placed each month in 2024?",
            "sql": "SELECT strftime('%Y-%m', order_date) AS month, COUNT(order_id) AS total_orders FROM orders WHERE strftime('%Y', order_date) = '2024' GROUP BY month ORDER BY month ASC;"
        },
        {
            "id": "ex_29",
            "question": "How many orders were placed in 2024?",
            "sql": "SELECT COUNT(order_id) AS orders_2024 FROM orders WHERE strftime('%Y', order_date) = '2024';"
        },
        {
            "id": "ex_30",
            "question": "What is the total revenue per month in 2024?",
            "sql": "SELECT strftime('%Y-%m', o.order_date) AS month, SUM(o.total_amount) AS monthly_revenue FROM orders o WHERE strftime('%Y', o.order_date) = '2024' AND o.status != 'canceled' GROUP BY month ORDER BY month ASC;"
        },
        {
            "id": "ex_31",
            "question": "Show the number of new customers registered each month.",
            "sql": "SELECT strftime('%Y-%m', created_at) AS month, COUNT(customer_id) AS new_customers FROM customers GROUP BY month ORDER BY month ASC;"
        },
        {
            "id": "ex_32",
            "question": "Find the total payment amount received in the last 30 days.",
            "sql": "SELECT SUM(amount) AS recent_revenue FROM payments WHERE payment_status = 'success' AND payment_date >= date('now', '-30 days');"
        },
    ]

    # Insert into ChromaDB
    collection.upsert(
        ids=[ex["id"] for ex in examples],
        documents=[ex["question"] for ex in examples],
        metadatas=[{"sql": ex["sql"]} for ex in examples]
    )

    print(f"✅ Successfully seeded {collection.count()} Few-Shot Question-SQL pairs into ChromaDB!")

if __name__ == "__main__":
    init_vector_db()